version: "2.3"
services:
  ontop:
    container_name: ontop
    image: oegdataintegration/ontop:4.0.3
    volumes:
      - ../data:/data
      - ../results/ontop:/results
      - ../mappings:/mappings
      - ../configs/ontop:/configs
    depends_on:
      - mysql
  rmlmapper:
    container_name: rmlmapper
    image: oegdataintegration/rmlmapper:4.9.1
    volumes:
      - ../data:/data
      - ../results/rmlmapper:/results
      - ../mappings:/mappings
      - ../configs/rmlmapper:/configs
    depends_on:
      - mysql
  rocketrml:
    container_name: rocketrml
    image: oegdataintegration/rocketrml:1.8.2
    volumes:
      - ../data:/data
      - ../results/rocketrml:/results
      - ../mappings:/mappings
      - ../configs/rocketrml:/configs
  sdmrdfizer:
    container_name: sdmrdfizer
    image: oegdataintegration/sdm-rdfizer:3.4
    volumes:
      - ../data:/data
      - ../results/sdmrdfizer:/results
      - ../mappings:/mappings
      - ../configs/sdmrdfizer:/configs
    depends_on:
      - mysql
  morphrdb:
    container_name: morphrdb
    image: oegdataintegration/morph-rdb:3.12.6
    volumes:
      - ../data:/data
      - ../results/morphrdb:/results
      - ../mappings:/mappings
      - ../configs/morphrdb:/configs
    depends_on:
      - mysql
  rmlstreamer:
    container_name: rmlstreamer
    image: oegdataintegration/rmlstreamer:2.0
    volumes:
      - ../data:/data
      - ../results/rmlstreamer:/results
      - ../mappings:/mappings
      - ../configs/rmlstreamer:/configs
  db2triples:
    container_name: db2triples
    image: oegdataintegration/dbtriples:2.3
    volumes:
      - ../data:/data
      - ../results/db2triples:/results
      - ../mappings:/mappings
      - ../configs/db2triples:/configs
    depends_on:
      - mysql
  carml:
    container_name: carml
    image: oegdataintegration/carml:0.3.1
    volumes:
      - ../data:/data
      - ../results/carml:/results
      - ../mappings:/mappings
      - ../configs/carml:/configs

  # MYSQL
  mysql:
    container_name: kgc-mysql
    image: mysql:8.0
    restart: always
    volumes:
     - /data/volumes:/var/lib/mysql
     - /data:/data    
    environment:
      MYSQL_ROOT_PASSWORD: r2rml
      MYSQL_USER: r2rml
      MYSQL_PASSWORD: r2rml
    ports:
      - "3306:3306"
    command: --sql_mode="ANSI_QUOTES,ALLOW_INVALID_DATES" 
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

networks:
  kgc_eval:
    driver: bridge    