version: "2.3"
services:
  ontop:
    container_name: ontop
    image: oegdataintegration/ontop:4.0.3
    volumes:
      - ../data:/data
      - ../results/ontop:/results
      - ../mappings:/mappings
      - ../configs/ontop:/configs
  rmlmapper:
    container_name: rmlmapper
    image: oegdataintegration/rmlmapper:4.9.1
    volumes:
      - ../data:/data
      - ../results/rmlmapper:/results
      - ../mappings:/mappings
      - ../configs/rmlmapper:/configs
  rocketrml:
    container_name: rocketrml
    image: oegdataintegration/rocketrml:1.8.2
    volumes:
      - ../data:/data
      - ../results/rocketrml:/results
      - ../mappings:/mappings
      - ../configs/rocketrml:/configs
  sdmrdfizer:
    container_name: sdmrdfizer
    image: oegdataintegration/sdm-rdfizer:3.4
    volumes:
      - ../data:/data
      - ../results/sdmrdfizer:/results
      - ../mappings:/mappings
      - ../configs/sdmrdfizer:/configs
  morphrdb:
    container_name: morphrdb
    image: oegdataintegration/morph-rdb:3.12.6
    volumes:
      - ../data:/data
      - ../results/morphrdb:/results
      - ../mappings:/mappings
      - ../configs/morphrdb:/configs
 
 