version: "2"
services:
  rmlmapper:
    container_name: rmlmapper
    image: oegdataintegration/rmlmapper:4.7
    shm_size: '50gb'
    volumes:
      - ../data:/data
      - ../results/rmlmapper:/results
      - ../mappings:/mappings
      - ./rmlmapper:/rmlmapper
  rocketrml:
    container_name: rocketrml
    image: oegdataintegration/rocketrml:1.5
    shm_size: '50gb'
    volumes:
      - ../data:/data
      - ../results/rocketrml:/results
      - ../mappings:/mappings
      - ./rocketrml:/rocketrml
  sdmrdfizer:
    container_name: sdmrdfizer
    image: oegdataintegration/sdmrdfizer:3.2
    shm_size: '50gb'
    volumes:
      - ../data:/data
      - ../results/sdmrdfizer:/results
      - ../mappings:/mappings
      - ./sdmrdfizer:/sdmrdfizer